services:
  - type: web
    name: safeguard-family-api
    repo: https://github.com/rupen-rakholiya-28/safeguard-family.git
    branch: main
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: PORT
        value: 8080