services:
  - type: web
    name: safeguard-family-api
    repo: https://github.com/rupen-rakholiya-28/safeguard-family.git
    branch: main
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: java -jar backend/target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod